# Generated by Django 5.1.5 on 2025-02-15 10:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('crop_heatmap_image', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('predictor_1', models.ImageField(blank=True, max_length=30, null=True, upload_to='')),
                ('predictor_2', models.ImageField(blank=True, max_length=30, null=True, upload_to='')),
                ('predictor_3', models.ImageField(blank=True, max_length=30, null=True, upload_to='')),
                ('heatmap_1', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('heatmap_2', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('heatmap_3', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
            ],
        ),
    ]
