# Generated by Django 5.1.5 on 2025-02-06 06:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('detected_image', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('heatmap_1', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('heatmap_2', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
                ('heatmap_3', models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path)),
            ],
        ),
    ]
