# Generated by Django 5.1.5 on 2025-01-22 10:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='performer',
            name='image',
        ),
        migrations.AddField(
            model_name='performer',
            name='detected_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='heatmap_1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='heatmap_2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='heatmap_3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
