# Generated by Django 5.1.5 on 2025-02-17 13:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='knn',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='lg',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='performer',
            name='mlp',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.get_upload_path),
        ),
    ]
